### ISSUE TITLE
[Bug]: DRPC enables on game\region change

### ISSUE THREAD

**Issue by LADIlib** [CollapseLauncher/Collapse#308] opened 2023-11-12 15:39 UTC
### Affected Version

1.71.15 Stable

### Bug Behavior

DRPC activity shows when game\region changes when its disabled in launcher settings

### Expected Behavior

it should be disabled even after changing region

### Steps to reproduce

1. Open launcher (pic. 1)
2. Check RPC status in discord (its disabled in launcher settings) (pic. 2,3)
3. Change game/region in launcher (pic. 4)
4. Check RPC status in discord (its still disabled in launcher settings) (pic. 5,6)

### Screenshot(s)

1
![image](https://github.com/CollapseLauncher/Collapse/assets/39984678/3a7a377e-f19e-4ceb-8362-4114cbdb5fef)

2
![image](https://github.com/CollapseLauncher/Collapse/assets/39984678/5719eae7-1e8f-4d51-a1ef-5672b5fba97c)

3
![image](https://github.com/CollapseLauncher/Collapse/assets/39984678/c5c6a180-b54f-483e-a286-725ca04af0c4)

4
![image](https://github.com/CollapseLauncher/Collapse/assets/39984678/2c3a26f8-c569-4c30-904a-f3c669b242c5)

5
![image](https://github.com/CollapseLauncher/Collapse/assets/39984678/4eb02799-a591-4517-bb95-c04dae6eccc8)

6
![image](https://github.com/CollapseLauncher/Collapse/assets/39984678/b3352957-4955-43c1-97d3-15464366cfb1)

**Comment by bagusnl** [comment] 2023-11-12 15:46
This has been fixed in #304 and the fix will be shipped in the next preview release alongside with #305
If you believe #304 (and the fix within its comment) is not the duplicate of this issue, please reopen the ticket and add the details on why,

Thank you for submitting bug reports for Collapse!

**Closed by bagusnl** 2023-11-12 15:46 UTC
Labels: Needs Triaging
