### ISSUE TITLE
[Bug]: false conection error when use custom DNS

### ISSUE THREAD

**Issue by AphelG7** [CollapseLauncher/Collapse#551] opened 2024-08-01 19:58 UTC
### Affected Version

1.80.16

### Bug Behavior

System.Threading.Tasks.TaskCanceledException: net_http_request_timedout, 60
 ---> System.TimeoutException: TaskCanceledException_ctor_DefaultMessage
 ---> System.Threading.Tasks.TaskCanceledException: TaskCanceledException_ctor_DefaultMessage
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage, Boolean, Boolean, CancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
   Exception_EndOfInnerExceptionStack
   Exception_EndOfInnerExceptionStack
   at System.Net.Http.HttpClient.HandleFailure(Exception, Boolean, HttpResponseMessage, CancellationTokenSource, CancellationToken, CancellationTokenSource)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
   at CollapseLauncher.FallbackCDNUtil.GetURLHttpResponse(HttpClient client, String url, HttpMethod httpMethod, CancellationToken token)
   at CollapseLauncher.FallbackCDNUtil.GetURLHttpResponse(String URL, CancellationToken token, Boolean isForceUncompressRequest)
   at CollapseLauncher.FallbackCDNUtil.GetHttpStreamFromResponse(String URL, CancellationToken token)
   at CollapseLauncher.Helper.Image.ImageLoaderHelper.TryDownloadToCompleteness(String url, FileInfo fileInfo, CancellationToken token)

### Expected Behavior

.

### Steps to reproduce

when use cloudflare DNS (1.1.1.1) or WARP the launcher popup this message but everthing looks ok. except for the popup i cant close
![image](https://github.com/user-attachments/assets/0b392c66-0c9c-4a60-a141-1cfc8eff1de0)

**Comment by bagusnl** [comment] 2024-08-03 16:46
It's not duplicate of that one, I'm sure there was one issue thread that actually duplicate of this but I forgot which one... Oh well.

We'll use this thread to follow up on the progress, @neon-nyan is working on implementing proxy support (which is what Cloudflare WARP uses) for every network access Collapse does
As this gonna need quite a lot of changes, this will take time and will be delivered in 1.81.x branch.

We will notify you again when a release containing the implementation is released

**Comment by bagusnl** [comment] 2024-08-04 16:50
Fixed in 1.81.1 https://github.com/CollapseLauncher/Collapse/releases/tag/CL-v1.81.1-pre
If you still have problem, reopen this ticket or open another one.

Thanks for the support <3

**Closed by bagusnl** 2024-08-04 16:50 UTC
Labels: Needs Triaging
