### ISSUE TITLE
[Bug]: anti cheat

### ISSUE THREAD

**Issue by 6ixcyths** [CollapseLauncher/Collapse#582] opened 2024-09-23 07:12 UTC
### Affected Version

Collapse 1.80.19

### Bug Behavior

when i try and open the game it instantly crashes due to an anti cheat error

### Expected Behavior

the game should have opened and ran smoothly

### Steps to reproduce

My experience 

1st open the game
2nd wait a second
3rd anti cheat crash

### Screenshot(s)

Uploading Desktop 2024.09.23 - 00.09.53.03.mp4…

**Comment by 6ixcyths** [comment] 2024-09-23 07:12
i forgot to mention this is with honkai star rail

**Comment by bagusnl** [comment] 2024-09-24 14:43
This doesn't seem to be caused by the launcher. Can you try launching HSR by directly running StarRail.exe instead and see if it works? If it does, then right after that, try using the launcher

**Comment by Seiko-Senpai** [comment] 2024-12-01 18:38
if you have the launch on startup setting enabled then thats what causes it, closing and reopening collapse can fix it (i had the same issue)

**Comment by shatyuka** [comment] 2024-12-20 16:28
@Seiko-Senpai Can not reproduce here. Are you using the latest version?

**Comment by Cryotechnic** [comment] 2024-12-22 16:20
@Seiko-Senpai Heyo, just chiming in, is the issue resolved on your end?

**Comment by Seiko-Senpai** [comment] 2024-12-22 20:04
@shatyuka @Cryotechnic yeah it stopped happening on my end a while before i commented. i made my reply since it was the exact same as what OP said.
from exactly what i remember
Enabling the Start collapse on PC startup setting turned on, then tryna launch HSR would cause the game to throw an ACE error, Closing Collapse and relaunching it would fix the issue however, but iirc HSR also removed ACE recently meaning that nobody should be able to get this error

i do however have a similar issue now where by the same steps, the game will launch however it will not have me signed into any accounts instead of crashing, same fix as stated for that anti cheat issue would cause me to be logged back into the accs
but its never bothered me enough to report the issue when id imagine someone else will have reported it

sorry for the delayed response, i dont check my github replies lol
but if you need more details lmk and ill try to be of help

**Comment by shatyuka** [comment] 2024-12-23 04:41
@Seiko-Senpai Yes HSR and ZZZ have removed the ACE anti-cheat, but HI3 does not yet. I tried it on HI3 and couldn't reproduce it either.

**Comment by Seiko-Senpai** [comment] 2024-12-23 05:46
@shatyuka afaik ZZZ never had ACE, it always used HoyoProtekt (pretty sure thats how they spelled it), but even back when i had the issue it was only on HSR it happened, never any of the others. My guess is it was an internal update that somehow broke things but one of the later updates either to collapse or hsr fixed it

**Comment by shatyuka** [comment] 2024-12-23 07:31
Closing this issue due to not reproducible. Feel free to reopen this once it happands again. :)

**Closed by shatyuka** 2024-12-23 07:31 UTC
Labels: Game: Honkai: Star Rail, Need User Confirmation
