### ISSUE TITLE
[Request]: Support Bilibili "region" client

### ISSUE THREAD

**Issue by LaoshuBaby** [CollapseLauncher/Collapse#279] opened 2023-09-30 03:22 UTC
### Is your request related to a problem?

No

### Describe your proposed solution

![图片](https://github.com/neon-nyan/Collapse/assets/42690037/5798091d-0b54-4127-953d-27b6747ed7b8)
Add a bilibili region below those two.

### Describe alternatives you've considered

Bilibili cooperates with mihoyo and has two servers in mainland China, "Celestia"(天空岛) and "Irminsul"(世界树). Bilibili is a danmaku video website, like a mixture of niconico in Japan and Youtube in the world.

https://genshin-impact.fandom.com/wiki/UID#Format

Among them, "Irminsul" is logged in using a bilibili account, not a mihoyo account. It has its own dedicated client, which is different from the one downloaded from the mihoyo official website in mainland China. Therefore it is often called bilibili version or "B服"

I've searched "BiliBili" or "B服" as keywords and found no issues related.

https://www.biligame.com/detail/?id=105667

Its client can be downloaded by clicking the blue button "下载" 

(This require a bilibili account, I can help with this, you can email to me: laoshubaby@protonmail.com )

![图片](https://github.com/neon-nyan/Collapse/assets/42690037/0b3df5a1-a86a-4d2c-b315-6ffa80f3b79a)

For some players, they have both Bilibili accounts and mihoyo accounts (aka official servers, "官服"), but the current collapse does not allow them to quickly switch between the two versions of the client (despite dozens of GB of game material files are consistent)

### Additional context

It seems that this is a distant future feature. Although this issue is opened, I have no expectations whether it can be realized. If the maintainer has no interest of supporting this version of the client, just close this issue

Thank you
φ(゜▽゜*)♪

**Comment by Cryotechnic** [comment] 2023-09-30 03:33
Hi there, just letting you know that, as you've said, this is a feature that may be implemented in the future. That being said, we need to investigate whether or not this is compatible with our current launcher architecture. One of the maintainers will be in touch via e-mail. 

Again, would like to re-iterate that the implementation of new regions is going to take some time, so don't expect it to be released in the 1.72 lifecycle. That being said, we'll do our best to provide an accurate answer regarding the implementation whenever possible. Thanks for opening this issue!

**Comment by sino1641** [comment] 2023-10-01 17:53
Hi @Cryotechnic ,
The biligame(China) channel download link of GI is as follows: 
GET https://line1-h5-pc-api.biligame.com/game/detail/gameinfo?game_base_id=105667 
Refer to `pc_download_link` and `pc_download_link2`
One more thing, download link for HSR is https://line1-h5-pc-api.biligame.com/game/detail/gameinfo?game_base_id=108586
But there is no need for HI3.
Hope my info could reduce your effort on it.

**Comment by LaoshuBaby** [comment] 2023-10-04 12:09
> One of the maintainers will be in touch via e-mail.

Sorry for my late response, I've replyed that email. Thank you all for hard work on Collapse.

**Comment by bagusnl** [comment] 2023-10-04 15:33
Hi, I have made the new metadatav2 json file here. Replace the files inside Collapse App Data Folder (go to Settings>Open App Data Folder), inside the `_metadata` folder.

Download the file here https://paste.bagelnl.my.id/pasta/mouse-goat-bison

Just make sure that since this have yet to be uploaded to the main metadata CDN, it will get replaced on next metadata update. If the Bilibili option suddenly missing, hit me up here.

The complete support for bilibili client might take awhile as it needs more ironing out to support the repair function and stuff so it will require an update to the Collapse client itself

**Comment by LaoshuBaby** [comment] 2023-10-06 03:34
Tested, can auto detect installed bili version (infact, its launcher ask me 150gb free space, so I copy a piece of the global version and rename as "YuanShen.exe" and "YuanShen_Data", then use its launcher fixed broken files)

![图片](https://github.com/CollapseLauncher/Collapse/assets/42690037/9912655b-079f-49fb-bf26-348410706579)

Collapse's timer inherit Mainland of China version's count value.

![图片](https://github.com/CollapseLauncher/Collapse/assets/42690037/c36e35db-44d4-4d91-9eb4-85d3a5a9bc0c)

I can enter the game, and Bilibili version inherit China version's graphic settings, such as resolution, and my changes in Bilibili version will affect in China version.

I still haven't tested HSR's bilibili version, but I guess it will work too.

**Comment by bagusnl** [comment] 2023-10-06 03:56
The entire game files for Mainland China and Bilibili clients are identical for both games, except the addition of Bilibili login SDK and different config.ini contents. Both clients shares its registry key in which stores the game config and also Collapse's region specific configs including the timer counter.

The current state of Collapse can take these metadata containing the Bilibili region (I have it dormant on my local repo, waiting for approval), just that it can't install and repair it properly due to how the Bilibili login SDK file is located in MHY's API.
It will take a little bit of time until we are ready to ship this to (at least preview) release, but I'm hoping somewhere next week along with HSR's update

**Comment by Cryotechnic** [comment] 2023-10-09 23:47
Early implementation available as of 1.72.4. Keeping this open while we work on full implementation.

**Comment by bagusnl** [comment] 2023-10-17 03:13
Just a heads up, the game repair for GI Bilibili client is up, though its not for HSR because of time constraint. Will try to grab it once my internet can handle it and I have the time

**Comment by PIut02** [comment] 2023-10-29 08:54
Like said above the entire game files for Mainland China and Bilibili clients are identical for both games, and I have noticed that Collapse has already implemented the conversion from Steam to Global version and from Global to SEA version. Is it possible to implement region switching within the same game directory? This can save a lot of disk space. The specific implementation method is as follows:
1. Add  '\Genshin Impact Game\YuanShen_Data\Plugins\PCGameSDK.dll' and '\Genshin Impact Game\sdk_pkg_version'.
2. Modify the second line of  '\Genshin Impact Game\config.ini', changing the channel to '14'.
These files together only take up about 5MB and are easy to implement, and to switch back to the Mainland China region, you simply need to delete the 'PCGameSDK.dll' and 'sdk_pkg_version' files, and then modify the second line of the 'config.ini' file to 'channel=1'.

**Comment by bagusnl** [comment] 2023-10-29 11:13
currently it is planned but not yet finished due to the rework needed for the method to work on our Hi3 converter

**Comment by bagusnl** [comment] 2023-10-29 16:32
> could this feature be implemented for Honkai Impact 3rd?
I don't think HI3 has bilibili client

**Comment by PIut02** [comment] 2023-10-29 16:56
> I'm not sure if there is a method of modifying the Mainland China client to work with bilibili's login system 🥲

HI3 does not support Bilibili SDK, so no modifications to any files are required. The only method to log in to Bilibili account on PC is by using the QR code scanning login method. For more details, you can refer to https://github.com/HonkaiScanner/bh3_login_simulation-memories.

**Comment by bagusnl** [comment] 2023-12-13 13:02
Eyyo, sorry for a long silence but Bilibili region implementation is done as of latest Collapse preview!
Repair/Cache is also done, it just the matter of we enabling it in our metadata.

Also, since Bilibili official launcher doesn't have event API (for the event list and image carousel), do you guys prefer it to be as is or you guys wants it too? (we can take it from Mainland China APIs)

**Comment by LaoshuBaby** [comment] 2023-12-13 15:18
> do you guys prefer it to be as is or you guys wants it too? (we can take it from Mainland China APIs)

![图片](https://github.com/CollapseLauncher/Collapse/assets/42690037/ed58c675-c7b6-467c-a0ca-af8a57a376ee)

Yeah, its launcher just has nothing

{{vote}} I tend to follow this design and hide the carousel and community links directly

**Comment by Cryotechnic** [comment] 2023-12-17 03:59
> > do you guys prefer it to be as is or you guys wants it too? (we can take it from Mainland China APIs)
> 
> ![图片](https://private-user-images.githubusercontent.com/42690037/290238104-ed58c675-c7b6-467c-a0ca-af8a57a376ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3ODU3NDUsIm5iZiI6MTcwMjc4NTQ0NSwicGF0aCI6Ii80MjY5MDAzNy8yOTAyMzgxMDQtZWQ1OGM2NzUtYzdiNi00NjdjLWEwY2EtYWY4YTU3YTM3NmVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDAzNTcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNjQzMDQyN2YyZGFkODRlZGJjMDcxMjgzNDE0NDRkMjA1ZGQxMDNhOGMxZGM1NWJiMTQ2YWY4ZjUwN2YwMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v4RD8wGybWq7B56rHht2eMddpoAFp2te-V1uQcVpckk)
> 
> Yeah, its launcher just has nothing
> 
> {{vote}} I tend to follow this design and hide the carousel and community links directly

Since there has been no activity or vote against the following, we can just go ahead and keep it without an event banner just like Hi3 Global. This could change in the future should the need arise.

**Comment by LaoshuBaby** [comment] 2024-07-04 11:49
Maybe this issue need to reopen because ZZZ also have a Bilibili version, I just found it released and downloadable.

* Game market download page: https://www.biligame.com/detail/?id=111210
* Metadata JSON: https://line1-h5-pc-api.biligame.com/game/detail/gameinfo?game_base_id=111210

Hope it also can be added but maybe **not such urgent**, I know there will be many task to do just after the official online those days.

**Comment by bagusnl** [comment] 2024-07-04 11:58
Hi^^ can you send the launcher link?
I can't download it from here, you can upload it on gofile.io or something

**Comment by BUnipendix** [comment] 2024-07-04 14:18
> Hi^^ can you send the launcher link?
> I can't download it from here, you can upload it on gofile.io or something
> 

[ZenlessZoneZerobilibili_setup_202406191429.exe](https://pkg.biligame.com/games/ZenlessZoneZerobilibili_setup_202406191429/796157/ZenlessZoneZerobilibili_setup_202406191429.exe)

**Comment by BUnipendix** [comment] 2024-07-04 14:24
> Hi^^ can you send the launcher link?
> I can't download it from here, you can upload it on gofile.io or something
> 

[ZenlessZoneZerobilibili_setup_202406191429.exe](https://gofile.io/d/61btny)

**Comment by bagusnl** [comment] 2024-08-19 14:45
Bilibili metadata is added for Preview users. Closing issue.

If there is any problem caused by this, feel free to make a new issue ticket, this ticket should be strictly for additional region request

**Closed by bagusnl** 2024-08-19 14:45 UTC
Labels: Enhancement, Fixed, Area: Preset Config, Area: Hi3Helper.Http, Area: Dispatcher Key, Area: UI/UX
