### ISSUE TITLE
[Bug]: Crash when using the sync function on a newly installed 1.82.1 Preview

### ISSUE THREAD

**Issue by Cactism** [CollapseLauncher/Collapse#607] opened 2024-11-18 23:47 UTC
### Affected Version

Collapse 1.82.1 Preview

### Bug Behavior

After entering my credentials, an error will be spat out :(

### Expected Behavior

The database should be connected successfully, like in the image below:
![image](https://github.com/user-attachments/assets/c96dd0fd-887d-4614-a478-5e486675f4f6)

### Steps to reproduce

1. Install [1.82.1 Preview](https://github.com/CollapseLauncher/Collapse/releases/tag/CL-v1.82.1-pre) using the [installer](https://github.com/CollapseLauncher/Collapse/releases/download/CL-v1.82.1-pre/CL-1.82.1-preview_Installer.exe)
2. Enable the sync database feature and enter your credentials
3. Validate settings

### Screenshot(s)

https://github.com/user-attachments/assets/2b61e227-3910-4e08-b58e-11a77fa1d51f

In Windows Sandbox:
![image](https://github.com/user-attachments/assets/7b3de998-0dd8-49a9-97d2-9767b88709c8)

### Additional Information

Full error stack:
```
System.Exception: Failed to connect to the database, see error(s) below:
 ---> System.DllNotFoundException: Unable to load DLL 'csharp_bindings' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at Libsql.Client.DatabaseWrapper.OpenRemoteDatabase(DatabaseClientOptions options, Error& error)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Libsql.Client.DatabaseWrapper.Open()
   at Libsql.Client.DatabaseClient.Create(Action`1 configure)
   at CollapseLauncher.Helper.Database.DbHandler.Init(Boolean redirectThrow, Boolean bypassEnableFlag) in C:\projects\collapse\CollapseLauncher\Classes\Helper\Database\DBHandler.cs:line 146
   at CollapseLauncher.Pages.SettingsPage.ValidateAndSaveDbButton_Click(Object sender, RoutedEventArgs e) in C:\projects\collapse\CollapseLauncher\XAMLs\MainApp\Pages\SettingsPage.xaml.cs:line 1486
   Exception_EndOfInnerExceptionStack
```

**Comment by Cryotechnic** [comment] 2024-11-18 23:49
CC @bagusnl @neon-nyan

**Comment by bagusnl** [comment] 2024-11-18 23:52
Is this reproducable outside sandbox environment?

**Comment by Cactism** [comment] 2024-11-18 23:53
Yes; the video I posted above is done on a physical machine

**Comment by Cactism** [comment] 2024-11-19 00:08
Although I'm not entirely sure if it's only reproducible on a completely fresh install of Windows as I tried reinstalling Collapse on my laptop (and deleted it's files in AppData\LocalLow) and it worked correctly, like in the image I posted above

**Comment by bagusnl** [comment] 2024-11-19 00:09
Can you checck if the "csharp_bindings.dll" file really does not exist next to CollapseLauncher.exe ?

**Comment by Cactism** [comment] 2024-11-19 00:19
![image](https://github.com/user-attachments/assets/648b2fd7-0c50-4954-af77-4756e189a446)
It exists!

**Comment by bagusnl** [comment] 2024-11-19 00:24
Try installing vcredist
https://github.com/abbodi1406/vcredist/releases/tag/v0.85.0

**Comment by Cactism** [comment] 2024-11-19 00:36
> Try installing vcredist https://github.com/abbodi1406/vcredist/releases/tag/v0.85.0
It looked like that's all that was needed! After installing vcredist it worked as expected
![image](https://github.com/user-attachments/assets/340d8552-a80c-4982-b634-62d6a2849686)

**Comment by bagusnl** [comment] 2024-11-19 00:37
Noted, will add a note for it in the error log.
I'll keep this thread open until next preview

**Comment by bagusnl** [comment] 2024-11-19 01:09
Notes: csharp_bindings dependency walker
![image](https://github.com/user-attachments/assets/db4cbf26-cea3-47dd-97a1-d1556f678db2)

**Comment by Cryotechnic** [comment] 2024-12-22 16:00
Closing since new release.

**Closed by Cryotechnic** 2024-12-22 16:00 UTC
Labels: Bug, Fixed, Area: Runtime, Priority: Medium
