### ISSUE TITLE
[Bug]: Opening games using the collapse protocol doesn't update Discord RPC

### ISSUE THREAD

**Issue by MiekoHikari** [CollapseLauncher/Collapse#402] opened 2024-02-13 11:32 UTC
### Affected Version

1.73.3 Preview

### Bug Behavior

Launched the game with:
> Collapse://open -g 2 -r Global

But Discord RPC was stuck at Honkai Impact 3rd (what I was last playing using collapse)

### Expected Behavior

Collapse Discord RPC show Honkai: Star Rail status

### Steps to reproduce

1. Launch Collapse and set game to any game
2. Close Collapse (or keep it open, it doesn't matter)
3. Launch Collapse to open any other game (using Collapse://protocol)
4. Check Discord, presence stuck at game you opened at step 1

### Screenshot(s)

Recording of reproducing the steps: 
https://github.com/CollapseLauncher/Collapse/assets/77004524/44654b40-493b-4245-a538-78834b7f08c9

### Additional Information

DxDiag: [DxDiag.txt](https://github.com/CollapseLauncher/Collapse/files/14258943/DxDiag.txt)
Latest Logs: [log-2024-02-13-pre1.73.3-id1.log](https://github.com/CollapseLauncher/Collapse/files/14258945/log-2024-02-13-pre1.73.3-id1.log)

**Comment by shatyuka** [comment] 2024-02-13 11:39
The Discord RPC feature is currently under refactoring, I'll take a look at it later.
CC @gablm

**Comment by BobbyWibowo** [comment] 2024-03-02 01:51
@gablm Hi there, is this confirmed to also be fixed when launching via command line parameters? (e.g., Add to Steam shortcuts)

If I understood correctly, fix for this one should've been shipped alongside 1.73.4 Preview.

Steps to reproduce is the same as the original post, except step 3 being launching the games via Steam's shortcuts instead.

---

Or is it related with this particular line in the change log?
> For Custom Discord Client users, the current arRPC client that is used to get the RPC information for clients such as Vesktop, ArmCord, etc. has a bug pertaining to the update rate of the status, which can in turn cause the Discord status to appear "stuck" and not update. Please wait for the fix to be merged to the main repository. For custom client developers, please refer to https://github.com/OpenAsar/arrpc/pull/71

Since I do happen to be using Vesktop.

**Comment by bagusnl** [comment] 2024-03-02 01:58
Please try with official discord client, if it still doesn't update then its gonna be on the command line issue

**Comment by BobbyWibowo** [comment] 2024-03-02 03:31
@bagusnl Can confirm still happens with official client!

**Comment by bagusnl** [comment] 2024-03-02 03:32
Cc @gablm could it be something i accidentally fucked up in the codeQA?

**Comment by gablm** [comment] 2024-03-02 12:34
> @gablm Hi there, is this confirmed to also be fixed when launching via command line parameters? (e.g., Add to Steam shortcuts)

Hi!
I actually forgot to fix it when redirection doesn't happen (AKA when Collapse is not opened already).

@BobbyWibowo can you try this build?
https://nightly.link/CollapseLauncher/Collapse/actions/runs/8122717076/collapse_x64-Release_net8.0-windows10.0.22621.0_448ff7788ddb497e24118883f0d91366672c18bc.zip

You can unzip it anywhere.
To test it you can either:
 - add some regions to Steam (you will need to add them again from the stable/preview version later)
**or**
 - use the terminal and the command ```CollapseLauncher.exe open --game (0-2) --region (0-6, dependent on the game)```

**Comment by BobbyWibowo** [comment] 2024-03-03 18:22
@gablm From a few quick tests with "Add to Steam" shortcuts, I can confirm that build appears to be working just fine, even with Vesktop 🎉

**Closed** 2024-03-04 20:15 UTC
Labels: Bug, Area: Runtime, Area: Launcher

**Comment by gablm** [comment] 2024-03-04 20:21
Thanks for testing and confirming the fix works!
