### ISSUE TITLE
[Bug]: Too frequency about net_http_request_timeout error report

### ISSUE THREAD

**Issue by peach-water** [CollapseLauncher/Collapse#546] opened 2024-07-29 16:52 UTC
### Affected Version

Collapse 1.80.16

### Bug Behavior

I'm just downloading the upgrade package for Star Rail, the network is full used and there is no network bandwith left for collapse, so the collapse keep reporting this error too frequency to use the software.

### Expected Behavior

It should appear as a message, rather than taking over the entire interface, making it completely impossible to operate the software. 

### Steps to reproduce

1. just disconnect the software from the network.

### Screenshot(s)

![Uploading 2024-07-30 00-48-06_07-30_00-49-12.gif…]()

### Additional Information

just like the previous version maybe before 1.70 ? I love that version of the error alert style.

**Comment by peach-water** [comment] 2024-07-29 16:57
![test2](https://github.com/user-attachments/assets/bbbcf5d6-a48c-46c1-961c-dbf05f669037)

upload issue gif

**Comment by peach-water** [comment] 2024-07-29 17:00
> Hi there, Can you copy the error details here?

System.Threading.Tasks.TaskCanceledException: net_http_request_timedout, 60
 ---> System.TimeoutException: TaskCanceledException_ctor_DefaultMessage
 ---> System.Threading.Tasks.TaskCanceledException: TaskCanceledException_ctor_DefaultMessage
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage, Boolean, Boolean, CancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
   Exception_EndOfInnerExceptionStack
   Exception_EndOfInnerExceptionStack
   at System.Net.Http.HttpClient.HandleFailure(Exception, Boolean, HttpResponseMessage, CancellationTokenSource, CancellationToken, CancellationTokenSource)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
   at CollapseLauncher.FallbackCDNUtil.GetURLHttpResponse(HttpClient client, String url, HttpMethod httpMethod, CancellationToken token)
   at CollapseLauncher.FallbackCDNUtil.GetURLHttpResponse(String URL, CancellationToken token, Boolean isForceUncompressRequest)
   at CollapseLauncher.FallbackCDNUtil.GetHttpStreamFromResponse(String URL, CancellationToken token)
   at CollapseLauncher.Helper.Image.ImageLoaderHelper.TryDownloadToCompleteness(String url, FileInfo fileInfo, CancellationToken token)

This is the error information.

**Comment by neon-nyan** [comment] 2024-07-29 17:07
This caused by some background sprites (like Image Carousel, Social Media/QR Code Icons) were failed due to timeout. For now,  the fix should be applied in the next release and we have pushed a fix in this commit:
https://github.com/CollapseLauncher/Collapse/commit/08ab87471371fc659d0b471ffb1449fbd7518b01

For now, please ensure to clean the image files by going to the "App Settings" menu => Click "Clear Image Files" button. Then restart the launcher.

**Comment by peach-water** [comment] 2024-07-29 17:11
Just now, I didn't have this error after downloading the upgrade package. it just a little UX|UI Bugs. Hopefully this feature can be improved in near future. 
🙌And thanks for your approaching.

**Closed** 2024-07-30 05:04 UTC
Labels: Bug, Fixed, Area: UI/UX
