### ISSUE TITLE
[Bug]: Honkai Star Rail - Unhandled Error

### ISSUE THREAD

**Issue by Wizkiller96** [CollapseLauncher/Collapse#356] opened 2024-01-04 14:50 UTC
### Affected Version

Collapse 1.72.14

### Bug Behavior

Not sure if there is a fix for this but I didn't see any open issues about it or if there was one open then they got a different error message than mine. I should note the game still launches even with this error message popping up so not sure which game settings are effected by it.

`System.Exception: Due to miHoYo/Cognosphere A/B testing, Collapse currently does not support reading thefollowing key: App_Settings_h2319593470

This may also cause the modifications of Game Settings through this page to behave unexpectedly.

We apologize for the inconvenience we may have caused. Please try again later.
`

### Expected Behavior

To be able to switch to Honkai Star Rail and not have this error message pop up every time.

### Steps to reproduce

1. Open Collapse Launcher 1.72.14
2. Select Honkai Star Rail
3. An error should pop up saying the message I posted above.

**Comment by bagusnl** [comment] 2024-01-04 14:57
Thank you for submitting bug report for Collapse!
Oh, I think we might have put the warning label into the wrong page 😓 
We will check on it!
This error was caused by our misplaced warning check put on because of HoYo's A/B testing on their configuration saving mechanism on Star Rail. The new format is not supported due to something weird in the game code.

If you are bothered by the error message, you can wipe the configuration registry under `HKEY_CURRENT_USER/Software/Cognosphere/{either Star Rail or 崩坏：星穹铁道 depending on your installed region}`, you have to delete the entire subfolder of it (make sure you export it as backup just in case). Do note that this workaround will wipe all your settings including your login info, so you will have to login and set it up again.
![image](https://github.com/CollapseLauncher/Collapse/assets/28079733/9589898a-5c2a-4d21-bd4c-ca59806b6c65)



CC @Cryotechnic 
TODO:
Move A/B checker into the GSP .xaml.cs instead of the Registry Handlers to prevent warning be put on when the region is loaded.

**Comment by bagusnl** [comment] 2024-02-08 18:47
Should be fixed with last update on preview and next update for stable, sorry for taking a bit!

**Closed by bagusnl** 2024-02-08 18:47 UTC
Labels: Bug, Game: Honkai: Star Rail, Area: Game Settings
