### ISSUE TITLE
[Bug]: game somewhat glitching in some occasions

### ISSUE THREAD

**Issue by booldmaster** [CollapseLauncher/Collapse#455] opened 2024-04-19 15:05 UTC
### Affected Version

Collapse 1.73.8

### Bug Behavior

Honkai Impact always stutters/glitching in some screen. This does not happen on the Default Launcher however, which leads me to believe that it has something to do with Collapse Launcher

### Expected Behavior

No visual glitch occurs

### Steps to reproduce

There's alot of screen that occurs with the visual bug, but most notably when loading into a 'new' type of screen mode

Steps to reproduce on an example screen mode (Kolosten Screen)
1. Open 'Story' mode
2. Choose 'Thus Spoke Apocalypse' chapter
3. Enter the story 

### Additional Information

[DxDiag.txt](https://github.com/CollapseLauncher/Collapse/files/15041457/DxDiag.txt)

here's a clip of the visual bug (taken on Collapse)
https://github.com/CollapseLauncher/Collapse/assets/136598714/0f53434e-8512-4287-86d2-1f5a3e201cfb

for a comparison, same scenario taken on default launcher
https://github.com/CollapseLauncher/Collapse/assets/136598714/d3ed4e44-2746-40e4-a433-5f958afaf50b

**Comment by bagusnl** [comment] 2024-04-19 15:08
Hi~
Thank you for reporting the issue to us. 

This seems like something about the game windowing, can you share your game settings from Collapse ?

**Comment by booldmaster** [comment] 2024-04-19 15:11
Yes. This is my current settings
![image](https://github.com/CollapseLauncher/Collapse/assets/136598714/254db91f-6d47-4333-9fc1-cc0055b43d5a)

**Comment by bagusnl** [comment] 2024-04-19 15:12
Try disabling `Use Exclusive Fullscreen` and see if it resolves the glitching

**Comment by booldmaster** [comment] 2024-04-19 15:14
Thank You! It does resolves the issue now

**Comment by bagusnl** [comment] 2024-04-19 15:19
Nice! So, for further references, this is caused by the game switching from/to windowed and full screen exclusive (FSE) state. While generally FSE state usually have better performance and latency, this switching will be noticeable as you have experienced. We don't know why the game would switch the display mode for entering/closing a scene menu but that's on HoYo side as it can't be (easily and safely) fixed externally.

Let us know if you have any more issue/improvement for Collapse and thank you~

**Closed by bagusnl** 2024-04-19 15:19 UTC
Labels: Needs Triaging
