### ISSUE TITLE
[Bug]: Genshin Impact Game Repair Not Working

### ISSUE THREAD

**Issue by Seiko-Senpai** [CollapseLauncher/Collapse#320] opened 2023-11-28 21:50 UTC
### Affected Version

1.71.16, 1.72.6

### Bug Behavior

Try to run the game repair from collapse and it throws an "Unexpected Error". 
System.IO.IOException: Cannot create a file when that file already exists.
   at System.IO.FileSystem.MoveFile(String, String, Boolean)
   at CollapseLauncher.GenshinRepair.TryMoveAudioPersistent(IEnumerable`1 assetIndex) in D:\a\Collapse\Collapse\CollapseLauncher\Classes\RepairManagement\Genshin\Check.cs:line 100
   at CollapseLauncher.GenshinRepair.TryMovePersistentToStreamingAssets(IEnumerable`1 assetIndex) in D:\a\Collapse\Collapse\CollapseLauncher\Classes\RepairManagement\Genshin\Check.cs:line 65
   at CollapseLauncher.GenshinRepair.Check(List`1 assetIndex, CancellationToken token) in D:\a\Collapse\Collapse\CollapseLauncher\Classes\RepairManagement\Genshin\Check.cs:line 34
   at CollapseLauncher.GenshinRepair.CheckRoutine() in D:\a\Collapse\Collapse\CollapseLauncher\Classes\RepairManagement\Genshin\GenshinRepair.cs:line 81
   at CollapseLauncher.Interfaces.ProgressBase`2.TryRunExamineThrow(Task`1 action) in D:\a\Collapse\Collapse\CollapseLauncher\Classes\Interfaces\Class\ProgressBase.cs:line 513
   at CollapseLauncher.GenshinRepair.StartCheckRoutine(Boolean useFastCheck) in D:\a\Collapse\Collapse\CollapseLauncher\Classes\RepairManagement\Genshin\GenshinRepair.cs:line 50
   at CollapseLauncher.Pages.RepairPage.RunCheckRoutine(Object sender, Boolean isFast, Boolean isMainButton) in D:\a\Collapse\Collapse\CollapseLauncher\XAMLs\MainApp\Pages\RepairPage.xaml.cs:line 63

### Expected Behavior

To repair the game in the event of corrupt/missing data

### Steps to reproduce

1. launch game repair

### Additional Information

GR works for Honkai Impact and Star Rail however, but i know for a fact my genshin has some corrupt data, i just dont wanna use the official launcher to repair it

**Comment by bagusnl** [comment] 2023-12-03 22:08
Thank you for the follow up! @neon-nyan has worked on the fix for this issue.
The issue is caused by a misconfiguration in our code when moving the file from Persistent to StreamingAssets for some base game files that got misplaced there. Commit https://github.com/CollapseLauncher/Collapse/commit/a7e2d24fbc9215955e1ad36442b913da6481e138 should fix it and it will be shipped on next preview quite soon!

Thank you for reporting the issue and sorry for quite a slow response time <3

**Closed** 2023-12-04 05:29 UTC
Labels: Need Further Investigation/Attention
