### ISSUE TITLE
[Bug]: Star Rail BiliBili - Dispatch Server Channel Incorrect

### ISSUE THREAD

**Issue by studiobuttermedia** [CollapseLauncher/Collapse#550] opened 2024-08-01 15:19 UTC
### Affected Version

1.80.17 (REL) - 1.81.0 (PRE) - 1.81.0d (DBG)

### Bug Behavior

Repair Function isn't working correctly for HSR - BiliBili Server.
Stable and Preview behavior: Repair Function somehow fall back to Star Rail - Global Repair Data on BiliBili Server. Cache Update Function Errors
Debug: Repair and Cache Update Functions display error

VS Debug: Collapse Repair and Cache Update function for Star Rail - BiliBili was using the Dispatch URL with the wrong `channel` and `sub_channel` ids.

### Expected Behavior

Repair and Cache Update Function should be using the correct metadata.

Debug: By using the correct `channel` and `sub_channel` ids

### Steps to reproduce

Do a repair on Star Rail - BiliBili.

If on Debug, Console should give out all the dispatch correctly with the Dispatch URL using the correct URL and it's JSON prefixes

### Additional Information

[Debug Log](https://paste.bagelnl.my.id/p/fish-lion-zebra)

**Comment by neon-nyan** [comment] 2024-08-02 19:18
# Update - 2024/08/03
The fix for this issue has been fixed alongside this change: https://github.com/CollapseLauncher/Collapse/compare/93cd7d382567...39b863d4d03e
For the current stable/preview version, the fix has already been pushed via metadata update.

Can you confirm if the issue is fixed?

**Comment by studiobuttermedia** [comment] 2024-08-02 19:47
The repair function seems to be working correctly with the only issue being the necessary "unused" files for Cutscenes problem that all regions having.
![image](https://github.com/user-attachments/assets/b3d9344f-2fd3-4161-bec7-50d4ad61f5fd)

Otherwise, it's working as intended.

**Comment by neon-nyan** [comment] 2024-08-02 19:58
Fixed the files incorrectly being detected as "Unused".
https://github.com/CollapseLauncher/Collapse/commit/0c0950893307fff1487d633beddf52e44816e5d2

The part of the code should've been removed as the behavior with the in-game update has been changed since v2.2

**Comment by bagusnl** [comment] 2024-08-02 23:25
Note:
Changes needed to fix this can't be (easily) back ported to stable. Either:
1. Notify HSR: Bilibili user to move to stable
2. Back port (by cherry picking) all necessary metadata changes to stable

**Comment by Cryotechnic** [comment] 2024-08-25 05:43
Fixed in https://github.com/CollapseLauncher/CollapseLauncher-ReleaseRepo/commit/d69b8bb7e84da0dfb026a9a998ca394de15ccdb8

**Closed by Cryotechnic** 2024-08-25 05:43 UTC
Labels: Fixed, Area: Preset Config, Game: Honkai: Star Rail, Area: Mirror/API Server, Area: Dispatcher Key
