### ISSUE TITLE
[Bug]: TrayIcon initialization issue

### ISSUE THREAD

**Issue by omarelmahdy2200** [CollapseLauncher/Collapse#615] opened 2024-12-04 16:52 UTC
### Affected Version

1.82.3 Preview [Codename: Natlan]

### Bug Behavior

[Bug]: Whenever i minimize the collapse launcher it just continue working in the task manager but i can't open it anymore through the tasks bar or by opening the exe again. I have to end it from the task manager then open it again and never minimize it to be able to use it.

### Expected Behavior

Just minimzed to tray so i could open it again whenever i need to.

### Steps to reproduce

1. Minimize 
2. done

### Screenshot(s)

![2024-12-04 18_55_01-](https://github.com/user-attachments/assets/e5d4e512-ed90-4f3a-a0f6-ed7cbf0fcb52)

_No response_

### Additional Information
[log-2024-12-04-pre1.82.3-id1-18-53-32.log](https://github.com/user-attachments/files/18012708/log-2024-12-04-pre1.82.3-id1-18-53-32.log)

[DxDiag.txt](https://github.com/user-attachments/files/18011580/DxDiag.txt)

**Comment by shatyuka** [comment] 2024-12-04 17:38
Reproduced: Windows 10 22H2
```
[Erro]   [01:35:47.649]  Failed when trying to send notification!
System.InvalidOperationException: TrayIcon is not created.
   at H.NotifyIcon.Core.TrayIcon.EnsureCreated() in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 697
   at H.NotifyIcon.Core.TrayIcon.ShowNotification(String title, String message, NotificationIcon icon, Nullable`1 customIconHandle, Boolean largeIcon, Boolean sound, Boolean respectQuietTime, Boolean realtime, Nullable`1 timeout) in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 577
   at CollapseLauncher.TrayIcon.ShowNotification(String title, String message, NotificationIcon icon, Nullable`1 customIconHandle, Boolean largeIcon, Boolean sound, Boolean respectQuietTime, Boolean realtime) in C:\projects\collapse\CollapseLauncher\XAMLs\MainApp\TrayIcon.xaml.cs:line 350
```

**Comment by bagusnl** [comment] 2024-12-04 21:42
I'm not sure if that log is related. IIRC that notification failing issue is reproducable on all builds and practically because the trayicon takes awhile to load. So if you use StartOnTray system, it will always send a toast when it gets minimized but the TrayIcon should claim the window back when it gets loaded. 

@omarelmahdy2200 are you using any type of custom Windows ISO /having it heavily modified?

**Comment by omarelmahdy2200** [comment] 2024-12-04 22:41
Now that you mention that, yes i'm using the compact Ghostspectre Win10 22h2.
But that problem is only in the 18.82.3 that i installed just today, it wasn't present in the other version but i installed this one because you said that the others may have some kind of problems with updating hsr.

**Comment by shatyuka** [comment] 2024-12-05 19:24
The tray icon was not created successfully because the API `Shell_NotifyIcon(NIM_ADD)` call failed.
It has something to do with the path to the program when the tray icon was first created. It's reproducible on both Windows 10 and Windows 7 (via a small demo, of course), as described in MSDN document below. But this problem doesn't exist on Windows 11.

[NOTIFYICONDATAW Troubleshooting](https://learn.microsoft.com/en-us/windows/win32/api/shellapi/ns-shellapi-notifyicondataw#troubleshooting)
> The binary file that contains the icon was moved. The path of the binary file is included in the registration of the icon's GUID and cannot be changed. Settings associated with the icon are preserved through an upgrade only if the file path and GUID are unchanged. If the path must be changed, the application should remove any GUID information that was added when the existing icon was registered. Once that information is removed, you can move the binary file to a new location and reregister it with a new GUID. Any settings associated with the original GUID registration will be lost.
> This also occurs in the case of a side-by-side installation. When dealing with a side-by-side installation, new versions of the application should update the GUID of the binary file.
> Note: The only exception to a moved file occurs when both the original and moved binary files are [Authenticode](https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/ms537359(v=vs.85))-signed by the same company. In that case, settings are preserved through the move.

In fact we will delete the previously created icon before creating the tray icon to avoid this problem, but unfortunately the delete operation failed as well :(

Will look at it in detail over the weekend.

**Comment by bagusnl** [comment] 2024-12-06 09:41
Affected users please try debug build below
(do not try the AOT one)
https://github.com/CollapseLauncher/Collapse/actions/runs/12196233789

**Comment by omarelmahdy2200** [comment] 2024-12-06 16:24
![image](https://github.com/user-attachments/assets/2fc9d192-dabb-4907-8f32-6f71bbabc024)


Yes it works. Appericate your effort

**Comment by bagusnl** [comment] 2024-12-06 23:10
Thanks for the confirmation. The fix is in commit https://github.com/CollapseLauncher/Collapse/commit/2f84fc01c1d045cab724848aa12be0b417a4e30e

Background: back when we used Squirrel as update manager, the path to the app is dynamic and keeps changing. Which is annoying because even after getting code signing (thanks SignPath!) the TrayIcon cannot save its state (position and hidden state) after an update. So, I made the GUID static for every instance count Collapse has. And it definitely worked as we never got complaints about TrayIcon and based on my own tests (W11 and W10 LTSC) there were no errors regarding it, until today.

Apparently as Shatyuka has mentioned, somewhere in Windows mechanism, it doesn't like a staticly assigned GUID. But in the typical Microsoft fashion, the method that creates TrayIcon never sends any errors, so we never know.

(TL;DR) This commit reverts the static GUID for TrayIcon in Windows 10, the state should not changed as we moved to Velopack update manager and the path to Collapse is static

**Comment by shatyuka** [comment] 2024-12-07 17:39
Just by judging Windows11 may not be very accurate. I remember that Windows 11 22H2 had a refactoring of the tray icon (if I remember correctly), which may be the reason for the difference in behavior.

**Comment by shatyuka** [comment] 2024-12-07 18:58
> But in the typical Microsoft fashion, the method that creates TrayIcon never sends any errors, so we never know.

It does have. `H.NotifyIcon` chose to catch this exception and then let the debugger stop here.

https://github.com/HavenDV/H.NotifyIcon/blob/8773b98709886dbd766c3baac2dfa086a7b835ee/src/libs/H.NotifyIcon.Shared/TaskbarIcon.cs#L58-L65
https://github.com/CollapseLauncher/H.NotifyIcon/blob/58e360b0a5d7094144ef3a45614198ff7e941aae/src/libs/H.NotifyIcon/Core/TrayIcon.cs#L324-L333

**Comment by neon-nyan** [comment] 2024-12-22 16:15
As per mentioned by @shatyuka, this issue has been fixed on the latest preview and stable release. Feel free to re-open this issue if you still have the problem occur.

**Closed by neon-nyan** 2024-12-22 16:15 UTC
Labels: Bug, Fixed, Area: Runtime, Priority: High
