### ISSUE TITLE
[Bug]: Genshin Impact's HDR calibration images wouldn't load in the Game Settings page.

### ISSUE THREAD

**Issue by 3stantedja** [CollapseLauncher/Collapse#296] opened 2023-10-17 09:08 UTC
### Affected Version

Collapse 1.72.5-PRE

### Bug Behavior

Going into the "Game Settings" page, and then expanding the "Enable HDR" option would show the settings for Max Luminosity, Scenery Brightness, and UI Brightness with the expected layout and spacing; however, the images themselves will not load (ie. it will show empty spaces).

Looking into the Collapse Console shows me the following:
![image](https://github.com/CollapseLauncher/Collapse/assets/3055647/30c9da7f-c570-49bc-97af-f307b5539975)

### Expected Behavior

The HDR calibration images should show as seen in https://github.com/CollapseLauncher/Collapse/pull/270#issuecomment-1731766394

### Steps to reproduce

1. Make sure HDR is turned on (in Windows 11: Settings → System → Display → Use HDR)
2. Open Collapse Launcher
3. Make sure the game selected is Genshin Impact (region does not matter)
4. Navigate to Game Settings
5. Expand the Enable HDR option

### Screenshot(s)

![image](https://github.com/CollapseLauncher/Collapse/assets/3055647/d29f3bb8-b086-4146-bfe4-f8b6ddec7b8b)
![image](https://github.com/CollapseLauncher/Collapse/assets/3055647/0cd7a743-f461-4ac7-9b0a-5be56787a9c8)

### Additional Information

Logs:
[log-2023-10-17-pre1.72.5-id1.log](https://github.com/CollapseLauncher/Collapse/files/12926556/log-2023-10-17-pre1.72.5-id1.log)

System info:
[DxDiag.txt](https://github.com/CollapseLauncher/Collapse/files/12926570/DxDiag.txt)

Note that HDR is enabled as shown here:
<img width="902" alt="Screenshot 2023-10-17 031838" src="https://github.com/CollapseLauncher/Collapse/assets/3055647/b4f5160e-4c82-4c61-9691-b06d87adb99c">

**Comment by shatyuka** [comment] 2023-10-17 09:28
under investigation

**Comment by shatyuka** [comment] 2023-10-17 12:54
Reproduced under Windows App SDK 1.3, while 1.4 works fine. Probably an upstream issue.

**Comment by bagusnl** [comment] 2023-10-17 13:00
As a note, we have always been using 1.3 for quite a long time due to numerous issues like items rendering out of border, window size, and some other xaml issues. Though if you're okay for updating the WinAppSDK to 1.4 and heavily test it then we can do it @shatyuka

I currently have some IRL stuff so it would take a long time for me to sort thru, if you're up for the task then go ahead and make a new branch in this repo for it

**Comment by bagusnl** [comment] 2023-10-17 13:15
It's a really dumb thing with Visual Studio "clean" button. It doesn't fully clean the project.
You have to open "ClearCache.bat" we have in the root of our project and it should fully clean everything without the need to reclone the repo

**Comment by shatyuka** [comment] 2023-10-17 13:56
This is because trimming is turned on, and the Win2D Canvas is using reflection internally, causing the type to be unavailable.
After replacing with the untrimmed .netcore library `Microsoft.Graphics.Canvas.dll` and `System.Runtime.dll`, it works.

**Comment by bagusnl** [comment] 2023-10-17 13:59
Ah... Another trimming issue. Then it should be a one line change in CollapseLauncher.csproj and a test on published build. I don't have a proper HDR monitor so I can't test it myself

**Comment by shatyuka** [comment] 2023-10-17 14:18
Resolved after deleting this line:
https://github.com/CollapseLauncher/Collapse/blob/77f625c7c64f702dbc15c9a107d1b7c3fa43f95a/CollapseLauncher/CollapseLauncher.csproj#L136

**Comment by bagusnl** [comment] 2023-10-17 14:26
Shatyuka has pushed the commit for the fix but unfortunately the build that will fix this might take a while to be released. In the meantime you can go to the run here https://github.com/CollapseLauncher/Collapse/actions/runs/6548600810/job/17783640073 and once it's done you can download its artifacts and replace the contents of your app-1.73.5 folder in your Collapse installation folder with the contents of that artifact.

Thank you for reporting the issue and using Collapse Launcher <3

Reopening the issue until the fix is released into main prod Preview branch

**Comment by 3stantedja** [comment] 2023-10-17 23:08
![image](https://github.com/CollapseLauncher/Collapse/assets/3055647/d1d3e9f5-7dbb-450a-bac6-e6c42df67cff)
![image](https://github.com/CollapseLauncher/Collapse/assets/3055647/adc6c5b8-9821-4150-9c86-3d6e113ac9f3)

it works now! thanks so much!

**Comment by bagusnl** [comment] 2023-11-28 04:55
Should be fixed in 1.72.7 preview

**Closed by bagusnl** 2023-11-28 04:55 UTC
Labels: Bug, Fixed, Game: Genshin Impact, Area: UI/UX
