### ISSUE TITLE
[Bug]: Video playback is choppy when using video backgrounds

### ISSUE THREAD

**Issue by devrim6** [CollapseLauncher/Collapse#452] opened 2024-04-12 11:40 UTC
### Affected Version

1.80.0-PRE

### Bug Behavior

Selecting a video as the background makes said video appear choppy with it pausing at fixed intervals.

### Expected Behavior

The video should play at the native fps with no hiccups.

### Steps to reproduce

Just add any video.

### Screenshot(s)

https://github.com/CollapseLauncher/Collapse/assets/72068078/9bd9c8c1-b4f5-4d39-9375-f825217b69c1

### Additional Information

[DxDiag.txt](https://github.com/CollapseLauncher/Collapse/files/14958184/DxDiag.txt)

[log-2024-04-12-prevUnknown-id1.log](https://github.com/CollapseLauncher/Collapse/files/14958212/log-2024-04-12-prevUnknown-id1.log)

**Comment by neon-nyan** [comment] 2024-04-12 12:28
Hi @devrim6,

Thank you for reporting this issue. For further investigation, can you send us the background video you use?

**Comment by devrim6** [comment] 2024-04-12 14:09
> Hi @devrim6,
> 
> Thank you for reporting this issue. For further investigation, can you send us the background video you use?

Sure, though this issue persists with any kind of video I try. 

https://github.com/CollapseLauncher/Collapse/assets/72068078/4cb09468-5d62-4c70-b4b6-761b00138abd

**Comment by neon-nyan** [comment] 2024-04-12 18:27
Thanks for the response @devrim6,

Seems like it's not media specific issue but can you try these builds and tell if one or both of these builds have the same stutter issue.
#### [Canary Build with FFmpeg Codec](https://cdn.discordapp.com/attachments/1121278963176718386/1228410391382458408/canary-build-with-FFmpeg_202404130109.7z?ex=662bf154&is=66197c54&hm=42ecd38fb7c96b8f79eec39e858dfe19e3f903fa8ca6bf148869f6e7de7a0eb7&)
#### [Canary Build with Windows Media Foundation Codec](https://cdn.discordapp.com/attachments/1121278963176718386/1228410391063822376/canary-build-with-MediaFoundation_202404130109.7z?ex=662bf153&is=66197c53&hm=d022e9c864e094f119d6f394983e592ef883fdd3f912882b8c04dca6659444d3&)

**Comment by devrim6** [comment] 2024-04-12 18:49
Unfortunately both builds show the same issue. The Windows Media build threw an error regarding mpeg-dash, but using any other video resulted in the same bug.

`System.FormatException: The video format is in "MPEG-DASH" format, which is unsupported.
   at CollapseLauncher.Helper.Background.Loaders.MediaPlayerLoader.EnsureIfFormatIsDashOrUnsupported(Stream stream) in E:\myGit\Collapse\CollapseLauncher\Classes\Helper\Background\Loaders\MediaPlayerLoader.cs:line 261
   at CollapseLauncher.Helper.Background.Loaders.MediaPlayerLoader.LoadAsync(String filePath, Boolean isImageLoadForFirstTime, Boolean isRequestInit, CancellationToken token) in E:\myGit\Collapse\CollapseLauncher\Classes\Helper\Background\Loaders\MediaPlayerLoader.cs:line 196
   at CollapseLauncher.Helper.Background.BackgroundMediaUtility.LoadBackground(String mediaPath, Boolean isRequestInit, Boolean isForceRecreateCache) in E:\myGit\Collapse\CollapseLauncher\Classes\Helper\Background\BackgroundMediaUtility.cs:line 335
   at CollapseLauncher.MainPage.CustomBackgroundChanger_Event(Object sender, BackgroundImgProperty e) in E:\myGit\Collapse\CollapseLauncher\XAMLs\MainApp\MainPage.xaml.cs:line 451`

**Comment by neon-nyan** [comment] 2024-04-12 19:28
Noted. Seems like the stuttering issue caused by WinUI.
I will be keeping this issue open until we find a way to fix it or waiting for Microsoft to fix this issue.

Regarding to that exception you're seeing is intentional since I've recently added a check if the .mp4 video format is using MPEG-DASH container, which is by default unsupported for users who don't install additional codec pack.

**Comment by Scighost** [comment] 2024-04-16 14:09
@devrim6 Hi, you could use `ffmpeg` to repackage video stream.

``` shell
 ffmpeg -i .\322010765-4cb09468-5d62-4c70-b4b6-761b00138abd.mp4 -c copy output.mp4
```


https://github.com/CollapseLauncher/Collapse/assets/61003590/b0ac98c4-3464-496b-b65e-070a05095566

**Comment by devrim6** [comment] 2024-04-16 17:22
@Scighost That did not fix the issue either. I tried repackaging other videos with ffmpeg but I got the same result.

**Comment by bagusnl** [comment] 2024-04-16 23:29
I can't replicate the stutter with both a 4K60 VP9 22.4Mbps video, nor video that was provided above (after converted by SciGhost)
Tho I do notice a slight stutter on the 4K60 when the video was on my hard drive, moving it to SSD completely fixes it (could be because I was on the middle of a defrag too but eh)

System:
Ryzen 7 5700X
Radeon RX6600
W11 23H2
Collapse 1.80.0-Pre release version

**Comment by neon-nyan** [comment] 2024-04-19 18:48
Can you try this build? It's using async FileStream and bigger buffer being set (64 KB instead of 4 KB)
### [Canary Build with Async + Big Buffer](https://cdn.discordapp.com/attachments/1121278963176718386/1230952024472813568/canary-build_asyncBufferedBGStream.7z?ex=66353068&is=6622bb68&hm=af001016a5ddd3825ba1da6c3ae2c41bae34df44d88136f753dc548f353fd0a0&)

**Comment by devrim6** [comment] 2024-04-20 01:38
@neon-nyan This build did not do it either. I have tested background videos on other machines as well and it worked there, so it might just be something with my system, though not sure what. Here are the logs in case you need them.
[log-2024-04-20-pre1.80.0-id0.log](https://github.com/CollapseLauncher/Collapse/files/15046529/log-2024-04-20-pre1.80.0-id0.log)

**Comment by bagusnl** [comment] 2024-09-18 15:52
Closed as stale and cannot reproduced. Shall there is a new clue, please reopen the issue.
Thanks for supporting Collapse Launcher!

**Closed by bagusnl** 2024-09-18 15:52 UTC
Labels: Bug, Need Further Investigation/Attention, Area: WinUI/CsWinRT/WindowsAppSDK
